spring:
  thymeleaf:
    cache: false  # Thymeleaf ??? ?? ???? (?? ???)
  web:
    resources:
      cache:
        period: 0 # ?? ??? ?? ???? (?? ???)

server:
  port: 8080

logging:
  level:
    root: INFO  # ?? ?? ?? ??
    org.springframework.web: DEBUG  # WebClient? ?? ??? ?? ??


webclient:
  base-url: http://apis.data.go.kr  # WebClient ?? URL
  timeout:
    connect: 5000  # ?? ???? (???)
    read: 10000    # ?? ???? (???)

